language: node_js
node_js: 10.15.0

install:
  - npm install

before_script:
  ### 将文章中的图片资源复制到发布目录中
  # 1. 清空source/images目录
  - rm -rf source/images
  # 2. 创建 source/images目录
  - mkdir source/images
  # 3. 将各个文件夹中的图片文件拷贝到发布目录source/images中
  - cp -r `find notes -name *.png -o -name *.jpg` source/images

  ### 将要发布的文章复制到发布目录中
  # 1. 清空source/_posts目录
  - rm -rf source/_posts
  # 2. 创建 source/_posts目录
  - mkdir source/_posts
  # 3. 把需要发布的文章拷贝到发布目录中^开始 $结尾 .任意一个字符
  - cp -r `grep ^layout:.post$ -rl notes` source/_posts
  # 4. 替换发布目录中文章中图片资源的地址
  - a=`grep ./assets -rl source/_posts`
  - if [ ! -z $a ]; then sed -i -e "s~./assets~/images~g"; fi;

  ### 设置git相关的配置信息
  # 初始化 git配置
  - git config user.name "lleej"
  - git config user.email "lleej@qq.com"
  # 替换_config.yml 文件中发布库的地址
  - sed -i -e "s~git@github.com:lleej/lleej.github.io.git~https://${ACCESS_TOKEN}@github.com/lleej/lleej.github.io.git~" _config.yml

script:
  - hexo clean
  - hexo g
  - hexo d

after_script:


